{"uuid": "6978c9be-c901-4ddc-b2bb-f4021268fe7b", "children": ["a8d6abb8-35be-4e0e-8f13-a8f894df45a3"], "befores": [{"name": "initialization_driver", "status": "passed", "start": 1686326128348, "stop": 1686326130902}], "afters": [{"name": "initialization_driver::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: Unable to execute request for an existing session: Unable to find session with ID: e9577b3b27b07a23947b799f48e26364\nBuild info: version: '4.10.0', revision: 'c14d967899'\nSystem info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '19.0.1'\nDriver info: driver.version: unknown\n\n", "trace": "  File \"C:\\Users\\HP\\PycharmProjects\\pythonProject\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\HP\\PycharmProjects\\pythonProject\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\HP\\PycharmProjects\\pythonProject\\src\\PageObjectModel\\Tests\\conftest.py\", line 54, in initialization_driver\n    web_driver.quit()\n  File \"C:\\Users\\HP\\PycharmProjects\\pythonProject\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 468, in quit\n    self.execute(Command.QUIT)\n  File \"C:\\Users\\HP\\PycharmProjects\\pythonProject\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\HP\\PycharmProjects\\pythonProject\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1686326173891, "stop": 1686326173915}], "start": 1686326128348, "stop": 1686326173915}